"""
Group Project: Group 5
Created by :   Antara Saha               
Specification: As we are integrating the data from multiple source. Ther are some mismatch in the college names.
               They don't have any specific pattern we can code to match the data. Due to which this script is 
               manually updating the college name with the required one.
"""

from os import replace
import pandas as pd

def collegename_clean():
    data_n = pd.read_csv('temp_niche_college_data.csv',encoding = "ISO-8859-1")

    data_n.loc[data_n['College Name'] == "University of California - Berkeley",	"College Name"] = 	"University of California, Berkeley"
    data_n.loc[data_n['College Name'] == "Columbia University",	"College Name"] = 	"Columbia University in the City of New York"
    data_n.loc[data_n['College Name'] == "University of Michigan - Ann Arbor",	"College Name"] = 	"University of Michigan"
    data_n.loc[data_n['College Name'] == "University of Minnesota Twin Cities",	"College Name"] = 	"University of Minnesota-Twin Cities"
    data_n.loc[data_n['College Name'] == "University of California - Los Angeles",	"College Name"] = 	"University of California, Los Angeles"
    data_n.loc[data_n['College Name'] == "University of Texas - Austin",	"College Name"] = 	"The University of Texas at Austin"
    data_n.loc[data_n['College Name'] == "University of Wisconsin",	"College Name"] = 	"University of Wisconsin-Madison"
    data_n.loc[data_n['College Name'] == "University of California - San Diego",	"College Name"] = 	"University of California, San Diego"
    data_n.loc[data_n['College Name'] == "University of Illinois Urbana-Champaign",	"College Name"] = 	"University of Illinois at Urbana-Champaign"
    data_n.loc[data_n['College Name'] == "University of California - Davis",	"College Name"] = 	"University of California, Davis"
    data_n.loc[data_n['College Name'] == "University of Maryland - College Park",	"College Name"] = 	"University of Maryland"
    data_n.loc[data_n['College Name'] == "Rutgers University - New Brunswick",	"College Name"] = 	"Rutgers, The State University of New Jersey"
    data_n.loc[data_n['College Name'] == "University of California - Irvine",	"College Name"] = 	"University of California, Irvine"
    data_n.loc[data_n['College Name'] == "University of Arizona",	"College Name"] = 	"The University of Arizona"
    data_n.loc[data_n['College Name'] == "Texas AandM University",	"College Name"] = 	"Texas A&M University"
    data_n.loc[data_n['College Name'] == "University of Utah",	"College Name"] = 	"The University of Utah"
    data_n.loc[data_n['College Name'] == "University of Colorado - Boulder",	"College Name"] = 	"University of Colorado Boulder"
    data_n.loc[data_n['College Name'] == "Indiana University - Bloomington",	"College Name"] = 	"Indiana University Bloomington"
    data_n.loc[data_n['College Name'] == "University of California - Santa Barbara",	"College Name"] = 	"University of California, Santa Barbara"
    data_n.loc[data_n['College Name'] == "University of Nebraska - Lincoln",	"College Name"] = 	"University of Nebraska-Lincoln"
    data_n.loc[data_n['College Name'] == "University of Massachusetts - Amherst",	"College Name"] = 	"University of Massachusetts Amherst"
    data_n.loc[data_n['College Name'] == "University of California - Riverside",	"College Name"] = 	"University of California, Riverside"
    data_n.loc[data_n['College Name'] == "Rice University",	"College Name"] = 	"William Marsh Rice University"
    data_n.loc[data_n['College Name'] == "University at Buffalo, SUNY",	"College Name"] = 	"University at Buffalo, State University of New York"
    data_n.loc[data_n['College Name'] == "University of California - Santa Cruz",	"College Name"] = 	"University of California, Santa Cruz"
    data_n.loc[data_n['College Name'] == "University of Tennessee",	"College Name"] = 	"The University of Tennessee, Knoxville"
    data_n.loc[data_n['College Name'] == "University of Oklahoma",	"College Name"] = 	"The University of Oklahoma"
    data_n.loc[data_n['College Name'] == "University of Tennessee - Martin",	"College Name"] = 	"The University of Tennessee at Martin"
    data_n.loc[data_n['College Name'] == "California State University - Northridge",	"College Name"] = 	"California State University, Northridge"
    data_n.loc[data_n['College Name'] == "San Jose State University",	"College Name"] = 	"San JosÃ© State University"
    data_n.loc[data_n['College Name'] == "University of Alabama - Birmingham",	"College Name"] = 	"University of Alabama at Birmingham"
    data_n.loc[data_n['College Name'] == "William and Mary",	"College Name"] = 	"College of William & Mary"
    data_n.loc[data_n['College Name'] == "Stony Brook University, SUNY",	"College Name"] = 	"Stony Brook University"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Milwaukee",	"College Name"] = 	"University of Wisconsin-Milwaukee"
    data_n.loc[data_n['College Name'] == "University of Texas - Dallas",	"College Name"] = 	"The University of Texas at Dallas"
    data_n.loc[data_n['College Name'] == "California State University - Long Beach",	"College Name"] = 	"California State University, Long Beach"
    data_n.loc[data_n['College Name'] == "Indiana University-Purdue University - Indianap…",	"College Name"] = 	"Indiana University - Purdue University Indianapolis"
    data_n.loc[data_n['College Name'] == "University at Albany, SUNY",	"College Name"] = 	"University at Albany, State University of New York"
    data_n.loc[data_n['College Name'] == "University of Maine",	"College Name"] = 	"The University of Maine"
    data_n.loc[data_n['College Name'] == "University of Nevada - Reno",	"College Name"] = 	"University of Nevada, Reno"
    data_n.loc[data_n['College Name'] == "California State University - Fullerton",	"College Name"] = 	"California State University, Fullerton"
    data_n.loc[data_n['College Name'] == "California Polytechnic State University (Cal Poly) - San Luis Obispo",	"College Name"] = 	"California Polytechnic State University, San Luis Obispo"
    data_n.loc[data_n['College Name'] == "University of Texas - San Antonio",	"College Name"] = 	"The University of Texas at San Antonio"
    data_n.loc[data_n['College Name'] == "Binghamton University, SUNY",	"College Name"] = 	"Binghamton University, State University of New York"
    data_n.loc[data_n['College Name'] == "University of Missouri - Kansas City",	"College Name"] = 	"University of Missouri-Kansas City"
    data_n.loc[data_n['College Name'] == "University of Texas - Arlington",	"College Name"] = 	"The University of Texas at Arlington"
    data_n.loc[data_n['College Name'] == "University of Nevada Las Vegas",	"College Name"] = 	"University of Nevada, Las Vegas"
    data_n.loc[data_n['College Name'] == "University of Montana",	"College Name"] = 	"The University of Montana"
    data_n.loc[data_n['College Name'] == "University of Massachusetts - Boston",	"College Name"] = 	"University of Massachusetts Boston"
    data_n.loc[data_n['College Name'] == "Embry-Riddle Aeronautical University - Daytona Beach",	"College Name"] = 	"Embry-Riddle Aeronautical University"
    data_n.loc[data_n['College Name'] == "University of Memphis",	"College Name"] = 	"The University of Memphis"
    data_n.loc[data_n['College Name'] == "University of Maryland, Baltimore",	"College Name"] = 	"University of Maryland, Baltimore County"
    data_n.loc[data_n['College Name'] == "University of North Carolina - Greensboro",	"College Name"] = 	"University of North Carolina at Greensboro"
    data_n.loc[data_n['College Name'] == "California State Polytechnic University - Pomona",	"College Name"] = 	"California State Polytechnic University, Pomona"
    data_n.loc[data_n['College Name'] == "California State University - Sacramento",	"College Name"] = 	"California State University, Sacramento"
    data_n.loc[data_n['College Name'] == "California State University - Chico",	"College Name"] = 	"California State University, Chico"
    data_n.loc[data_n['College Name'] == "University of Massachusetts - Lowell",	"College Name"] = 	"University of Massachusetts Lowell"
    data_n.loc[data_n['College Name'] == "The University of Akron",	"College Name"] = 	"University of Akron"
    data_n.loc[data_n['College Name'] == "University of Texas - El Paso",	"College Name"] = 	"The University of Texas at El Paso"
    data_n.loc[data_n['College Name'] == "University of Michigan - Dearborn",	"College Name"] = 	"University of Michigan-Dearborn"
    data_n.loc[data_n['College Name'] == "United States Military Academy at West Point",	"College Name"] = 	"United States Military Academy"
    data_n.loc[data_n['College Name'] == "Brigham Young University - Idaho",	"College Name"] = 	"Brigham Young University-Idaho"
    data_n.loc[data_n['College Name'] == "Rasmussen College - St. Cloud",	"College Name"] = 	"Rasmussen College"
    data_n.loc[data_n['College Name'] == "University of Missouri - St. Louis",	"College Name"] = 	"University of Missouri-St. Louis"
    data_n.loc[data_n['College Name'] == "CUNY Lehman College",	"College Name"] = 	"Lehman College, CUNY"
    data_n.loc[data_n['College Name'] == "California State University - San Bernardino",	"College Name"] = 	"California State University, San Bernardino"
    data_n.loc[data_n['College Name'] == "California State University - Fresno",	"College Name"] = 	"California State University, Fresno"
    data_n.loc[data_n['College Name'] == "University of California - Merced",	"College Name"] = 	"University of California, Merced"
    data_n.loc[data_n['College Name'] == "University of North Carolina - Wilmington",	"College Name"] = 	"University of North Carolina Wilmington"
    data_n.loc[data_n['College Name'] == "The University of Baltimore",	"College Name"] = 	"University of Baltimore"
    data_n.loc[data_n['College Name'] == "University of Colorado - Colorado Springs",	"College Name"] = 	"University of Colorado Colorado Springs"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Stevens Point",	"College Name"] = 	"University of Wisconsin-Stevens Point"
    data_n.loc[data_n['College Name'] == "University of Tulsa",	"College Name"] = 	"The University of Tulsa"
    data_n.loc[data_n['College Name'] == "California State University - Los Angeles",	"College Name"] = 	"California State University, Los Angeles"
    data_n.loc[data_n['College Name'] == "DeVry University - Illinois",	"College Name"] = 	"DeVry University"
    data_n.loc[data_n['College Name'] == "Trinity College - Connecticut",	"College Name"] = 	"Trinity College"
    data_n.loc[data_n['College Name'] == "Fairleigh Dickinson University - Metropolitan C…",	"College Name"] = 	"Fairleigh Dickinson University"
    data_n.loc[data_n['College Name'] == "University of Texas - Rio Grande Valley",	"College Name"] = 	"University of Texas Rio Grande Valley"
    data_n.loc[data_n['College Name'] == "California State University - San Marcos",	"College Name"] = 	"California State University San Marcos"
    data_n.loc[data_n['College Name'] == "St. John's University - New York",	"College Name"] = 	"St. John's University"
    data_n.loc[data_n['College Name'] == "Wheaton College - Illinois",	"College Name"] = 	"Wheaton College"
    data_n.loc[data_n['College Name'] == "California State University - Dominguez Hills",	"College Name"] = 	"California State University, Dominguez Hills"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Green Bay",	"College Name"] = 	"University of Wisconsin-Green Bay"
    data_n.loc[data_n['College Name'] == "SUNY Oswego",	"College Name"] = 	"State University of New York at Oswego"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Oshkosh",	"College Name"] = 	"University of Wisconsin-Oshkosh"
    data_n.loc[data_n['College Name'] == "California State University - Stanislaus",	"College Name"] = 	"California State University, Stanislaus"
    data_n.loc[data_n['College Name'] == "University of Hawaii - West Oahu",	"College Name"] = 	"University of Hawaii-West Oahu"
    data_n.loc[data_n['College Name'] == "Texas AandM University - Corpus Christi",	"College Name"] = 	"Texas A&M University-Corpus Christi"
    data_n.loc[data_n['College Name'] == "Union College - New York",	"College Name"] = 	"Union College"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - La Crosse",	"College Name"] = 	"University of Wisconsin-La Crosse"
    data_n.loc[data_n['College Name'] == "Lewis and Clark College",	"College Name"] = 	"Lewis & Clark College"
    data_n.loc[data_n['College Name'] == "California State University - East Bay",	"College Name"] = 	"California State University, East Bay"
    data_n.loc[data_n['College Name'] == "Tennessee Technological University",	"College Name"] = 	"Tennessee Tech University"
    data_n.loc[data_n['College Name'] == "Strayer University - Online",	"College Name"] = 	"Strayer University"
    data_n.loc[data_n['College Name'] == "University of Tennessee - Chattanooga",	"College Name"] = 	"The University of Tennessee at Chattanooga"
    data_n.loc[data_n['College Name'] == "Johnson and Wales University- Providence",	"College Name"] = 	"Johnson and Wales University"
    data_n.loc[data_n['College Name'] == "University of Louisiana - Lafayette",	"College Name"] = 	"University of Louisiana at Lafayette"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Whitewater",	"College Name"] = 	"University of Wisconsin-Whitewater"
    data_n.loc[data_n['College Name'] == "Pacific University Oregon",	"College Name"] = 	"Pacific University"
    data_n.loc[data_n['College Name'] == "SUNY New Paltz",	"College Name"] = 	"State University of New York at New Paltz"
    data_n.loc[data_n['College Name'] == "West Texas AandM University",	"College Name"] = 	"West Texas A&M University"
    data_n.loc[data_n['College Name'] == "University of Tampa",	"College Name"] = 	"The University of Tampa"
    data_n.loc[data_n['College Name'] == "University of Arkansas at Little Rock",	"College Name"] = 	"University of Arkansas for Medical Sciences"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Stout",	"College Name"] = 	"University of Wisconsin-Stout"
    data_n.loc[data_n['College Name'] == "California State University - Monterey Bay",	"College Name"] = 	"California State University, Monterey Bay"
    data_n.loc[data_n['College Name'] == "Texas Tech University",	"College Name"] = 	"Texas Tech University Health Sciences Center"
    data_n.loc[data_n['College Name'] == "Sewanee - The University of the South",	"College Name"] = 	"Sewanee: The University of the South"
    data_n.loc[data_n['College Name'] == "William Paterson University of New Jersey",	"College Name"] = 	"William Paterson University"
    data_n.loc[data_n['College Name'] == "College of Wooster",	"College Name"] = 	"The College of Wooster"
    data_n.loc[data_n['College Name'] == "SUNY Oneonta",	"College Name"] = 	"SUNY College at Oneonta"
    data_n.loc[data_n['College Name'] == "SUNY Potsdam",	"College Name"] = 	"The State University of New York at Potsdam"
    data_n.loc[data_n['College Name'] == "CUNY Hunter College",	"College Name"] = 	"Hunter College, CUNY"
    data_n.loc[data_n['College Name'] == "Bloomsburg University",	"College Name"] = 	"Bloomsburg University of Pennsylvania"
    data_n.loc[data_n['College Name'] == "Citadel Military College of South Carolina",	"College Name"] = 	"The Citadel, The Military College of South Carolina"
    data_n.loc[data_n['College Name'] == "University of Texas - Tyler",	"College Name"] = 	"The University of Texas at Tyler"
    data_n.loc[data_n['College Name'] == "St. Petersburg College",	"College Name"] = 	"St Petersburg College"
    data_n.loc[data_n['College Name'] == "Texas AandM University - Commerce",	"College Name"] = 	"Texas A&M University-Commerce"
    data_n.loc[data_n['College Name'] == "SUNY Brockport",	"College Name"] = 	"The College at Brockport"
    data_n.loc[data_n['College Name'] == "SUNY Fredonia",	"College Name"] = 	"State University of New York at Fredonia"
    data_n.loc[data_n['College Name'] == "Wheaton College - Massachusetts",	"College Name"] = 	"Wheaton College, Massachusetts"
    data_n.loc[data_n['College Name'] == "South University - Savannah",	"College Name"] = 	"South University"
    data_n.loc[data_n['College Name'] == "California State University - Channel Islands",	"College Name"] = 	"California State University Channel Islands"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Platteville",	"College Name"] = 	"University of Wisconsin-Platteville"
    data_n.loc[data_n['College Name'] == "University of North Carolina Asheville",	"College Name"] = 	"University of North Carolina at Asheville"
    data_n.loc[data_n['College Name'] == "Columbia College - Missouri",	"College Name"] = 	"Columbia College"
    data_n.loc[data_n['College Name'] == "California State University - Bakersfield",	"College Name"] = 	"California State University, Bakersfield"
    data_n.loc[data_n['College Name'] == "Augustana College - Illinois",	"College Name"] = 	"Augustana College"
    data_n.loc[data_n['College Name'] == "Concordia University - St. Paul",	"College Name"] = 	"Concordia University, St. Paul"
    data_n.loc[data_n['College Name'] == "Concordia University - Wisconsin",	"College Name"] = 	"Concordia University Wisconsin"
    data_n.loc[data_n['College Name'] == "Texas AandM University - Kingsville",	"College Name"] = 	"Texas A&M University-Kingsville"
    data_n.loc[data_n['College Name'] == "Springfield College - Massachusetts",	"College Name"] = 	"Springfield College"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Parkside",	"College Name"] = 	"University of Wisconsin-Parkside"
    data_n.loc[data_n['College Name'] == "Montana Technological University",	"College Name"] = 	"Montana Tech"
    data_n.loc[data_n['College Name'] == "Texas AandM International University",	"College Name"] = 	"Texas A&M International University"
    data_n.loc[data_n['College Name'] == "Flagler College - St. Augustine",	"College Name"] = 	"Flagler College"
    data_n.loc[data_n['College Name'] == "King University - Tennessee",	"College Name"] = 	"King University"
    data_n.loc[data_n['College Name'] == "St. Thomas University - Florida",	"College Name"] = 	"St. Thomas University"
    data_n.loc[data_n['College Name'] == "King's College - Pennsylvania",	"College Name"] = 	"King's College"
    data_n.loc[data_n['College Name'] == "Westminster College - Utah",	"College Name"] = 	"Westminster College"
    data_n.loc[data_n['College Name'] == "University of Louisiana - Monroe",	"College Name"] = 	"University of Louisiana at Monroe"
    data_n.loc[data_n['College Name'] == "Edinboro University",	"College Name"] = 	"Edinboro University of Pennsylvania"
    data_n.loc[data_n['College Name'] == "Robert Morris University - Pennsylvania",	"College Name"] = 	"Robert Morris University"
    data_n.loc[data_n['College Name'] == "Lincoln University of Pennsylvania",	"College Name"] = 	"Lincoln University"
    data_n.loc[data_n['College Name'] == "Westminster College - Pennsylvania",	"College Name"] = 	"Westminster College, Pennsylvania"
    data_n.loc[data_n['College Name'] == "Montana State University - Billings",	"College Name"] = 	"Montana State University Billings"
    data_n.loc[data_n['College Name'] == "East Stroudsburg University of Pennsylvania",	"College Name"] = 	"East Stroudsburg University"
    data_n.loc[data_n['College Name'] == "Alabama AandM University",	"College Name"] = 	"Alabama A&M University"
    data_n.loc[data_n['College Name'] == "New England Conservatory of Music",	"College Name"] = 	"New England Conservatory"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Superior",	"College Name"] = 	"University of Wisconsin-Superior"
    data_n.loc[data_n['College Name'] == "Sterling College - Kansas",	"College Name"] = 	"Sterling College"
    data_n.loc[data_n['College Name'] == "Marian University Indianapolis",	"College Name"] = 	"Marian University"
    data_n.loc[data_n['College Name'] == "SUNY Farmingdale State College",	"College Name"] = 	"Farmingdale State College"
    data_n.loc[data_n['College Name'] == "CUNY Brooklyn College",	"College Name"] = 	"Brooklyn College"
    data_n.loc[data_n['College Name'] == "Anderson University - Indiana",	"College Name"] = 	"Anderson University, Indiana"
    data_n.loc[data_n['College Name'] == "Metropolitan State University - Minnesota",	"College Name"] = 	"Metropolitan State University"
    data_n.loc[data_n['College Name'] == "Saint Mary's College - Indiana",	"College Name"] = 	"Saint Mary's College"
    data_n.loc[data_n['College Name'] == "Berkeley College - New York",	"College Name"] = 	"Berkeley College"
    data_n.loc[data_n['College Name'] == "Bennett College for Women",	"College Name"] = 	"Bennett College"
    data_n.loc[data_n['College Name'] == "Keiser University - Fort Lauderdale",	"College Name"] = 	"Keiser University"
    data_n.loc[data_n['College Name'] == "Saint Vincent College - Pennsylvania",	"College Name"] = 	"Saint Vincent College"
    data_n.loc[data_n['College Name'] == "SUNY Buffalo State College",	"College Name"] = 	"Buffalo State College"
    data_n.loc[data_n['College Name'] == "Southwestern College - Kansas",	"College Name"] = 	"Southwestern College"
    data_n.loc[data_n['College Name'] == "SUNY Alfred State College",	"College Name"] = 	"Alfred State College"
    data_n.loc[data_n['College Name'] == "University of St. Thomas - Minnesota",	"College Name"] = 	"University of St. Thomas"
    data_n.loc[data_n['College Name'] == "Northwood University - Midland",	"College Name"] = 	"Northwood University"
    data_n.loc[data_n['College Name'] == "Herzing University - Madison",	"College Name"] = 	"Herzing University"
    data_n.loc[data_n['College Name'] == "Aquinas College - Michigan",	"College Name"] = 	"Aquinas College"
    data_n.loc[data_n['College Name'] == "Emmanuel College - Massachusetts",	"College Name"] = 	"Emmanuel College"
    data_n.loc[data_n['College Name'] == "Monroe College - Bronx/New Rochelle",	"College Name"] = 	"Monroe College"
    data_n.loc[data_n['College Name'] == "University of St. Francis - Illinois",	"College Name"] = 	"University of St. Francis"
    data_n.loc[data_n['College Name'] == "CUNY John Jay College of Criminal Justice",	"College Name"] = 	"John Jay College of Criminal Justice"
    data_n.loc[data_n['College Name'] == "Trinity International University - Deerfield",	"College Name"] = 	"Trinity International University"
    data_n.loc[data_n['College Name'] == "Northwestern College - Iowa",	"College Name"] = 	"Northwestern College"
    data_n.loc[data_n['College Name'] == "Mount Saint Mary College - New York",	"College Name"] = 	"Mount Saint Mary College"
    data_n.loc[data_n['College Name'] == "Northern Vermont University - Johnson Campus",	"College Name"] = 	"Northern Vermont University"
    data_n.loc[data_n['College Name'] == "Bryan College - Tennessee",	"College Name"] = 	"Bryan College"
    data_n.loc[data_n['College Name'] == "St. Joseph's College - New York",	"College Name"] = 	"St. Joseph's College"
    data_n.loc[data_n['College Name'] == "Bryant and Stratton College - Buffalo",	"College Name"] = 	"Bryant and Stratton College"
    data_n.loc[data_n['College Name'] == "Anderson University - South Carolina",	"College Name"] = 	"Anderson University"
    data_n.loc[data_n['College Name'] == "Lancaster Bible College - Capital Seminary and …",	"College Name"] = 	"Lancaster Bible College"
    data_n.loc[data_n['College Name'] == "Bethany College - West Virginia",	"College Name"] = 	"Bethany College"
    data_n.loc[data_n['College Name'] == "The Chicago School of Professional Psychology -…",	"College Name"] = 	"The Chicago School of Professional Psychology"
    data_n.loc[data_n['College Name'] == "Dominican College of Blauvelt",	"College Name"] = 	"Dominican College"
    data_n.loc[data_n['College Name'] == "University of Saint Francis - Indiana",	"College Name"] = 	"University of Saint Francis"
    data_n.loc[data_n['College Name'] == "Mount Saint Mary's University - Los Angeles",	"College Name"] = 	"Mount Saint Mary's University"
    data_n.loc[data_n['College Name'] == "Nebraska Methodist College of Nursing and Allie…",	"College Name"] = 	"Nebraska Methodist College"
    data_n.loc[data_n['College Name'] == "Bethel University - Minnesota",	"College Name"] = 	"Bethel University"
    data_n.loc[data_n['College Name'] == "CUNY College of Staten Island",	"College Name"] = 	"College of Staten Island"
    data_n.loc[data_n['College Name'] == "CUNY York College",	"College Name"] = 	"York College"
    data_n.loc[data_n['College Name'] == "The King's College - New York",	"College Name"] = 	"The King's College"
    data_n.loc[data_n['College Name'] == "South College - Knoxville",	"College Name"] = 	"South College"
    data_n.loc[data_n['College Name'] == "Bethany College - Kansas",	"College Name"] = 	"Bethany College, Kansas"
    data_n.loc[data_n['College Name'] == "Humphreys University - Stockton and Modesto Cam…",	"College Name"] = 	"Humphreys University"
    data_n.loc[data_n['College Name'] == "Anna Maria College",	"College Name"] = 	"Maria College"
    data_n.loc[data_n['College Name'] == "CUNY Medgar Evers College",	"College Name"] = 	"Medgar Evers College"
    data_n.loc[data_n['College Name'] == "Emmanuel College - Georgia",	"College Name"] = 	"Emmanuel College, Georgia"
    data_n.loc[data_n['College Name'] == "Bethesda University of California",	"College Name"] = 	"Bethesda University"
    data_n.loc[data_n['College Name'] == "Penn State University",	"College Name"] = 	"University of Pennsylvania"
    data_n.loc[data_n['College Name'] == "University of Wisconsin - Eau Claire",	"College Name"] = 	"University of Wisconsin-Eau Claire"
    data_n.loc[data_n['College Name'] == "Assumption University",	"College Name"] = 	"Assumption College"
    data_n.loc[data_n['College Name'] == "Moravian University",	"College Name"] = 	"Moravian College"
    data_n.loc[data_n['College Name'] == "Washington and Jefferson College",	"College Name"] = 	"Washington & Jefferson College"
    data_n.loc[data_n['College Name'] == "Penn State",	"College Name"] = 	"Penn State University"

    data_n.to_csv('niche_college_data.csv',encoding='utf-8',index =False,header= True)

# Call the function
if __name__ == "__main__":
    collegename_clean()